################
# DrupalCI GitLabCI template
#
# Gitlab-ci.yml to replicate DrupalCI testing for Contrib
#
# With thanks to:
#   * The GitLab Acceleration Initiative participants
#   * DrupalSpoons
################

include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

.nightwatch-base:
  variables:
    OTELCOL_VERSION: "0.112.0"
    OTELCOL_BINARY_DIRECTORY: $CI_PROJECT_DIR/tests/fixtures/opentelemetry-collector
    # This variable is not available in the Nightwatch context.
    # @see https://www.drupal.org/project/gitlab_templates/issues/3485612
    # @todo Fix this when the issue is resolved.
    OTELCOL_LOG_FILE: /var/tmp/opentelemetry-collector.log
    OTELCOL_CONFIG_FILE: $CI_PROJECT_DIR/tests/fixtures/opentelemetry-collector/config.yaml
    DRUPAL_NIGHTWATCH_IGNORE_DIRECTORIES: node_modules,vendor,.*,sites/*/files,sites/*/private,sites/simpletest,test3

  before_script:
  # Download the opentelemetry-collector binary.
  # @todo Think about including the opentelemetry-collector into the image
  # to not download it on each run.
  - |
    cd $OTELCOL_BINARY_DIRECTORY && \
    curl --proto '=https' --tlsv1.2 -fL https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v${OTELCOL_VERSION}/otelcol_${OTELCOL_VERSION}_linux_amd64.tar.gz -o otelcol.tar.gz && \
    tar -xvf otelcol.tar.gz && \
    cd $CI_PROJECT_DIR

  # Create a log file for the opentelemetry-collector to fix permissions.
  # @todo Check why the file is not created by the opentelemetry-collector
  # and remove this workaround when fixed.
  - |
    touch $OTELCOL_LOG_FILE && chmod 666 $OTELCOL_LOG_FILE

  # Start the opentelemetry-collector instance in the background and wait
  # when it is initalized.
  - |
    ($OTELCOL_BINARY_DIRECTORY/otelcol --config $OTELCOL_CONFIG_FILE &) && \
    $CI_PROJECT_DIR/tests/fixtures/wait-port.sh 4318
